# app/docker-compose.yaml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: aps2542/dash-ml-app:a2.0
    environment:
      - HOST=0.0.0.0
      - PORT=80
    ports:
      - "8050:80"
    command: python code/app.py
