# app/docker-compose.yaml
version: "3.9"
services:
  web:
    build:
      context: ..
      dockerfile: ./app/.Dockerfile
    image: dash-ml-app
    ports:
      - "8050:8050"
    command: python code/app.py
